default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: pg_alyssa
  password: alyssa

development:
  <<: *default
  database: ah_blog_development

test:
  <<: *default
  database: ah_blog_test

production:
  <<: *default
  database: ah_blog_production
  username: ah_blog
  password: <%= ENV['AH_BLOG_DATABASE_PASSWORD'] %>
