# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b242031f07581def5a2ffa2d7509ab1ba0f3aea13f8c2e39064409c134f48ee480278dc8da17da4bd725b418b4a585ec6ba0a4a146184793fd5ca646c81e5b8

test:
  secret_key_base: 4afe50bfde468c15e165b2bc37d8167680143e1d36769f14dc2908edf4bdfc075c6ac676c8e9a41d08af51da61ac403086440df5d959cef3f211702c695246fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
